apiVersion: batch/v1
kind: Job
metadata:
  name: spawner-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: spawn-catalog-item
        command:
        - /bin/bash
        - '-c'
        - |
            set -x
            pip install passlib openshift
            git clone {{ $.Values.spawner.agnosticd.repoUrl }}
            cd agnosticd
            git checkout {{ $.Values.spawner.agnosticd.branch }}
            cd ..
            git clone {{ $.Values.spawner.catalogitems.repoUrl }}
            cp -r agnosticd/roles rhdp-catalog-items
            cp -r agnosticd/roles_ocp_workloads rhdp-catalog-items
            cp -r agnosticd/lookup_plugins rhdp-catalog-items
            cp agnosticd/ansible.cfg rhdp-catalog-items
            cd rhdp-catalog-items
            ansible-playbook -i localhost site.yaml -e "ACTION=create"
        image: quay.io/agnosticd/ee-multicloud:latest
      restartPolicy: Never
      serviceAccount: spawner-runner