{{- $tempGuid := randAlphaNum 5 -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: spawner-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: spawn-catalog-item
        command:
        - /bin/bash
        - '-c'
        - |
            set -x
            pip install passlib openshift
            git clone {{ $.Values.spawner.agnosticd.repoUrl }}
            cd agnosticd
            git checkout {{ $.Values.spawner.agnosticd.branch }}
            cd ..
            git clone {{ $.Values.spawner.catalogitem.repoUrl }}
            cp -r {{ $.Values.spawner.catalogitem.path }}/* agnosticd/ansible
            cd agnosticd/ansible
            GUID={{ $.Values.spawner.guid | default $tempGuid }}
            ansible-playbook -i localhost site.yaml -e "ACTION=create" -e "guid=$GUID" -e @extra_vars/variables.yaml
        image: quay.io/agnosticd/ee-multicloud:latest
      restartPolicy: Never
      serviceAccount: spawner-runner