apiVersion: batch/v1
kind: Job
metadata:
  name: spawner-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: spawn-catalog-item
        command:
        - /bin/bash
        - '-c'
        - |
            set -x
            pip install passlib openshift
            git clone {{ $.Values.spawner.agnosticd.repoUrl }}
            cd agnosticd
            git checkout {{ $.Values.spawner.agnosticd.branch }}
            cd ..
            git clone {{ $.Values.spawner.catalogitem.repoUrl }}
            cp -r agnosticd/ansible/roles {{ $.Values.spawner.catalogitem.name }}
            cp -r agnosticd/ansible/roles_ocp_workloads {{ $.Values.spawner.catalogitem.name }}
            cp -r agnosticd/ansible/lookup_plugins {{ $.Values.spawner.catalogitem.name }}
            cp agnosticd/ansible.cfg r{{ $.Values.spawner.catalogitem.name }}
            cd {{ $.Values.spawner.catalogitem.name }}
            ansible-playbook -i localhost site.yaml -e "ACTION=create"
        image: quay.io/agnosticd/ee-multicloud:latest
      restartPolicy: Never
      serviceAccount: spawner-runner